version: "3.7"

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped

  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  server:
    container_name: graphql_api
    build:
      context: ./api
    volumes:
      - "./api:/api"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    restart: always

  # client:
  #   container_name: web_app
  #   build:
  #     context: ./client
  #   volumes:
  #     - './client:/client'
  #   ports:
  #     - '3000:8080'
  #   depends_on:
  #     - server
  #   restart: always

volumes:
  postgres-data:
  server:
  # client:
